# Preprocessing a Geochemical Dataset

Real geochemical tables often need a few cleaning steps before plotting or analysis. This notebook shows the preprocessing tools in `geochem`.

The preprocessing functions work with `pandas.DataFrame` objects and modify the DataFrame in place. This is intentional: they clean column names, convert values, and add or update geochemical columns.

## Import Libraries and Load the Dataset

After installing `geochem`, import it directly. The example data are stored in this `docs/` folder.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

import geochem as gc

In [2]:
DOCS_DIR = Path.cwd()
if not (DOCS_DIR / "data_example.csv").exists():
    DOCS_DIR = Path.cwd() / "docs"

csv_file = DOCS_DIR / "data_example.csv"
df = pd.read_csv(csv_file)

df.head()

,Sample,Type,Description,Reference,Source,SiO2,Al2O3,TiO2,FeO,Fe2O3,...,Sm,Eu,Gd,Tb,Dy,Ho,Er,Tm,Yb,Lu
0,HOR-06-01,Lava,Conos perifericos.,"Ruprecht, 2012",Hornitos,53.55,17.42,0.81,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CLHE1,Lava,Conos perifericos.,"Ruprecht, 2012",Hornitos,54.35,17.76,0.83,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CLHE2,Lava,Conos perifericos.,"Ruprecht, 2012",Hornitos,54.08,17.02,0.79,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CLHE-TF-04,Lava,Conos perifericos.,"Ruprecht, 2012",Hornitos,51.51,13.99,0.64,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CLHW1,Lava,Conos perifericos.,"Ruprecht, 2012",Hornitos,53.73,17.91,0.88,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 129 entries, 0 to 128
Data columns (total 53 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sample       129 non-null    str
 1   Type         129 non-null    str
 2   Description  129 non-null    str
 3   Reference    129 non-null    str
 4   Source       129 non-null    str
 5   SiO2         129 non-null    float64
 6   Al2O3        129 non-null    float64
 7   TiO2         129 non-null    float64
 8   FeO          0 non-null      float64
 9   Fe2O3        31 non-null     float64
 10  FeOT         98 non-null     float64
 11  CaO          129 non-null    float64
 12  MgO          129 non-null    float64
 13  MnO          129 non-null    float64
 14  Na2O         129 non-null    float64
 15  K2O          129 non-null    float64
 16  P2O5         129 non-null    float64
 17  LOI          0 non-null      float64
 18  Sum          129 non-null    float64
 19  Cu           121 non-null    float64
 20  V            123 non-null    float64
 21  Cr           123 non-null    str
 22  Co           43 non-null     float64
 23  Ni           121 non-null    float64
 24  Zn           121 non-null    float64
 25  Rb           107 non-null    float64
 26  Sr           123 non-null    float64
 27  Y            63 non-null     float64
 28  Zr           123 non-null    float64
 29  Nb           123 non-null    float64
 30  Ba           123 non-null    float64
 31  Pb           98 non-null     float64
 32  Sc           107 non-null    float64
 33  Ga           88 non-null     float64
 34  Cs           63 non-null     float64
 35  Hf           57 non-null     float64
 36  Ta           62 non-null     float64
 37  Th           107 non-null    float64
 38  U            53 non-null     float64
 39  La           82 non-null     float64
 40  Ce           82 non-null     float64
 41  Pr           19 non-null     float64
 42  Nd           82 non-null     float64
 43  Sm           38 non-null     float64
 44  Eu           37 non-null     float64
 45  Gd           34 non-null     float64
 46  Tb           37 non-null     float64
 47  Dy           0 non-null      float64
 48  Ho           0 non-null      float64
 49  Er           19 non-null     float64
 50  Tm           34 non-null     float64
 51  Yb           38 non-null     float64
 52  Lu           32 non-null     float64
dtypes: float64(47), str(6)
memory usage: 53.5 KB

## Step 1: Strip Whitespace from Column Names

Some columns in the raw file have spaces at the end, for example `SiO2 `. These names will not match the standard names used by `geochem` until the spaces are removed.

In [4]:
print("Before:")
print(df.columns.to_list())

Before:
['Sample', 'Type', 'Description', 'Reference', 'Source', 'SiO2 ', 'Al2O3 ', 'TiO2 ', 'FeO', 'Fe2O3 ', 'FeOT', 'CaO ', 'MgO', 'MnO ', 'Na2O', 'K2O', 'P2O5', 'LOI', 'Sum', 'Cu', 'V', 'Cr', 'Co', 'Ni', 'Zn', 'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Ba', 'Pb', 'Sc', 'Ga', 'Cs', 'Hf', 'Ta', 'Th', 'U', 'La', 'Ce', 'Pr', 'Nd', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu']

In [5]:
gc.preproc_strip_whitespace(df)

Strip whitespaces from column names
>  column names before:
 ['Sample', 'Type', 'Description', 'Reference', 'Source', 'SiO2 ', 'Al2O3 ', 'TiO2 ', 'FeO', 'Fe2O3 ', 'FeOT', 'CaO ', 'MgO', 'MnO ', 'Na2O', 'K2O', 'P2O5', 'LOI', 'Sum', 'Cu', 'V', 'Cr', 'Co', 'Ni', 'Zn', 'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Ba', 'Pb', 'Sc', 'Ga', 'Cs', 'Hf', 'Ta', 'Th', 'U', 'La', 'Ce', 'Pr', 'Nd', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu']
>  column names after:
 ['Sample', 'Type', 'Description', 'Reference', 'Source', 'SiO2', 'Al2O3', 'TiO2', 'FeO', 'Fe2O3', 'FeOT', 'CaO', 'MgO', 'MnO', 'Na2O', 'K2O', 'P2O5', 'LOI', 'Sum', 'Cu', 'V', 'Cr', 'Co', 'Ni', 'Zn', 'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Ba', 'Pb', 'Sc', 'Ga', 'Cs', 'Hf', 'Ta', 'Th', 'U', 'La', 'Ce', 'Pr', 'Nd', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu']

In [6]:
print("After:")
print(df.columns.to_list())

After:
['Sample', 'Type', 'Description', 'Reference', 'Source', 'SiO2', 'Al2O3', 'TiO2', 'FeO', 'Fe2O3', 'FeOT', 'CaO', 'MgO', 'MnO', 'Na2O', 'K2O', 'P2O5', 'LOI', 'Sum', 'Cu', 'V', 'Cr', 'Co', 'Ni', 'Zn', 'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Ba', 'Pb', 'Sc', 'Ga', 'Cs', 'Hf', 'Ta', 'Th', 'U', 'La', 'Ce', 'Pr', 'Nd', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu']

## Step 2: Convert Geochemical Columns to Numeric Values

Geochemical data should be numeric. Some datasets include values such as `<0.5`, meaning the element was below the detection limit. `geochem` converts these values to half the detection limit, so `<0.5` becomes `0.25`.

Only recognized geochemical columns are converted. Metadata columns such as `Sample`, `Type`, and `Source` are left unchanged.

In [7]:
print(df["Cr"].head(10))
print(df["Cr"].dtype)

0     109
1     105
2     199
3    1209
4     122
5     139
6     169
7      70
8     203
9     221
Name: Cr, dtype: str
str

In [8]:
gc.preproc_make_numeric_columns(df)

Ensuring geochemical data columns are numeric
>  Processed/verified numeric columns: Cr (parsed)

In [9]:
print(df["Cr"].head(10))
print(df["Cr"].dtype)

0     109.0
1     105.0
2     199.0
3    1209.0
4     122.0
5     139.0
6     169.0
7      70.0
8     203.0
9     221.0
Name: Cr, dtype: float64
float64

## Step 3: Calculate Total Iron as FeO (`FeOT`)

`calculate_FeOT()` derives total iron as FeO from `FeO` and `Fe2O3`:

```text
FeOT = FeO + 0.8998 * Fe2O3
```

When a DataFrame already has a `FeOT` column, the function only fills values that are missing or equal to zero. Existing non-zero `FeOT` values are preserved.

In [10]:
fe_cols = [col for col in ["FeO", "Fe2O3", "FeOT"] if col in df.columns]
df[fe_cols].head(10)

   FeO  Fe2O3  FeOT
0  NaN    NaN  7.48
1  NaN    NaN  7.56
2  NaN    NaN  7.67
3  NaN    NaN  8.13
4  NaN    NaN  7.51
5  NaN    NaN  7.39
6  NaN    NaN  7.51
7  NaN    NaN  7.30
8  NaN    NaN  7.43
9  NaN    NaN  7.48

In [11]:
gc.preproc_calculate_feot(df)

Check columns with Fe oxides and calculate FeOT
.. FeO column in database
.. Fe2O3 column in database
.. FeOT column in database
.. Calculating FeOT where necessary

In [12]:
df[["FeO", "Fe2O3", "FeOT"]].head(10)

   FeO  Fe2O3  FeOT
0  NaN    NaN  7.48
1  NaN    NaN  7.56
2  NaN    NaN  7.67
3  NaN    NaN  8.13
4  NaN    NaN  7.51
5  NaN    NaN  7.39
6  NaN    NaN  7.51
7  NaN    NaN  7.30
8  NaN    NaN  7.43
9  NaN    NaN  7.48

## Run All Preprocessing Steps at Once

The convenience function `preproc()` runs the three steps in order:

1. strip whitespace from column names;
2. convert recognized geochemical columns to numeric values;
3. calculate `FeOT` where needed.

In [13]:
df2 = pd.read_csv(csv_file)
gc.preproc(df2)

Strip whitespaces from column names
>  column names before:
 ['Sample', 'Type', 'Description', 'Reference', 'Source', 'SiO2 ', 'Al2O3 ', 'TiO2 ', 'FeO', 'Fe2O3 ', 'FeOT', 'CaO ', 'MgO', 'MnO ', 'Na2O', 'K2O', 'P2O5', 'LOI', 'Sum', 'Cu', 'V', 'Cr', 'Co', 'Ni', 'Zn', 'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Ba', 'Pb', 'Sc', 'Ga', 'Cs', 'Hf', 'Ta', 'Th', 'U', 'La', 'Ce', 'Pr', 'Nd', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu']
>  column names after:
 ['Sample', 'Type', 'Description', 'Reference', 'Source', 'SiO2', 'Al2O3', 'TiO2', 'FeO', 'Fe2O3', 'FeOT', 'CaO', 'MgO', 'MnO', 'Na2O', 'K2O', 'P2O5', 'LOI', 'Sum', 'Cu', 'V', 'Cr', 'Co', 'Ni', 'Zn', 'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Ba', 'Pb', 'Sc', 'Ga', 'Cs', 'Hf', 'Ta', 'Th', 'U', 'La', 'Ce', 'Pr', 'Nd', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu']

Ensuring geochemical data columns are numeric
>  Processed/verified numeric columns: Cr (parsed)

Check columns with Fe oxides and calculate FeOT
.. FeO column in database
.. Fe2O3 column in database
.. FeOT column in database
.. Calculating FeOT where necessary

In [14]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 129 entries, 0 to 128
Data columns (total 53 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sample       129 non-null    str
 1   Type         129 non-null    str
 2   Description  129 non-null    str
 3   Reference    129 non-null    str
 4   Source       129 non-null    str
 5   SiO2         129 non-null    float64
 6   Al2O3        129 non-null    float64
 7   TiO2         129 non-null    float64
 8   FeO          0 non-null      float64
 9   Fe2O3        31 non-null     float64
 10  FeOT         129 non-null    float64
 11  CaO          129 non-null    float64
 12  MgO          129 non-null    float64
 13  MnO          129 non-null    float64
 14  Na2O         129 non-null    float64
 15  K2O          129 non-null    float64
 16  P2O5         129 non-null    float64
 17  LOI          0 non-null      float64
 18  Sum          129 non-null    float64
 19  Cu           121 non-null    float64
 20  V            123 non-null    float64
 21  Cr           123 non-null    float64
 22  Co           43 non-null     float64
 23  Ni           121 non-null    float64
 24  Zn           121 non-null    float64
 25  Rb           107 non-null    float64
 26  Sr           123 non-null    float64
 27  Y            63 non-null     float64
 28  Zr           123 non-null    float64
 29  Nb           123 non-null    float64
 30  Ba           123 non-null    float64
 31  Pb           98 non-null     float64
 32  Sc           107 non-null    float64
 33  Ga           88 non-null     float64
 34  Cs           63 non-null     float64
 35  Hf           57 non-null     float64
 36  Ta           62 non-null     float64
 37  Th           107 non-null    float64
 38  U            53 non-null     float64
 39  La           82 non-null     float64
 40  Ce           82 non-null     float64
 41  Pr           19 non-null     float64
 42  Nd           82 non-null     float64
 43  Sm           38 non-null     float64
 44  Eu           37 non-null     float64
 45  Gd           34 non-null     float64
 46  Tb           37 non-null     float64
 47  Dy           0 non-null      float64
 48  Ho           0 non-null      float64
 49  Er           19 non-null     float64
 50  Tm           34 non-null     float64
 51  Yb           38 non-null     float64
 52  Lu           32 non-null     float64
dtypes: float64(48), str(5)
memory usage: 53.5 KB

## Quick Check

After preprocessing, standard geochemical columns should be available with clean names and numeric dtypes.

In [15]:
major = gc.getnames_major()
print(major)
print()
print(df2[major].dtypes)

['SiO2', 'Al2O3', 'TiO2', 'FeOT', 'CaO', 'MgO', 'MnO', 'Na2O', 'K2O', 'P2O5']

SiO2     float64
Al2O3    float64
TiO2     float64
FeOT     float64
CaO      float64
MgO      float64
MnO      float64
Na2O     float64
K2O      float64
P2O5     float64
dtype: object

In [16]:
df2[major].head()

    SiO2  Al2O3  TiO2  FeOT   CaO    MgO   MnO  Na2O   K2O  P2O5
0  53.55  17.42  0.81  7.48  9.46   5.55  0.14  3.30  0.98  0.17
1  54.35  17.76  0.83  7.56  9.70   5.49  0.14  3.38  1.00  0.17
2  54.08  17.02  0.79  7.67  9.45   6.92  0.14  3.30  0.99  0.17
3  51.51  13.99  0.64  8.13  9.26  13.66  0.15  2.38  0.65  0.12
4  53.73  17.91  0.88  7.51  9.58   6.06  0.14  3.38  0.98  0.18